In [1]:
import pandas as pd
import numpy as np

In [6]:
df1=pd.read_csv("ipl_ds2.csv")
df2=pd.read_csv("ipl_images.csv")

In [14]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           605 non-null    int64
 1   Name                 605 non-null    str
 2   runs                 605 non-null    int64
 3   boundaries           605 non-null    int64
 4   balls_faced          605 non-null    int64
 5   wickets              605 non-null    float64
 6   balls_bowled         605 non-null    float64
 7   runs_conceded        605 non-null    float64
 8   matches              605 non-null    int64
 9   batting_avg          605 non-null    float64
 10  batting_strike_rate  605 non-null    float64
 11  boundaries_percent   605 non-null    float64
 12  bowling_economy      605 non-null    float64
 13  bowling_avg          605 non-null    float64
 14  bowling_strike_rate  605 non-null    float64
 15  catches              605 non-null    float64
 16  stumpings            605 non-null    float64
dtypes: float64(11), int64(5), str(1)
memory usage: 80.5 KB

In [15]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 261 non-null    int64
 1   Name               261 non-null    str
 2   longName           261 non-null    str
 3   battingName        261 non-null    str
 4   fieldingName       261 non-null    str
 5   imgUrl             261 non-null    str
 6   dob                261 non-null    str
 7   battingStyles      261 non-null    str
 8   longBattingStyles  261 non-null    str
 9   bowlingStyles      261 non-null    str
 10  longBowlingStyles  261 non-null    str
 11  playingRoles       237 non-null    str
 12  espn_url           261 non-null    str
dtypes: int64(1), str(12)
memory usage: 26.6 KB

In [11]:
df1.rename(columns={"player":"Name"},inplace=True)

In [16]:
print(df1.shape)
print(df2.shape)

(605, 17)
(261, 13)

In [19]:
df2.isnull().sum()

ID                    0
Name                  0
longName              0
battingName           0
fieldingName          0
imgUrl                0
dob                   0
battingStyles         0
longBattingStyles     0
bowlingStyles         0
longBowlingStyles     0
playingRoles         24
espn_url              0
dtype: int64

In [20]:
df1["Name"] = df1["Name"].str.strip()
df2["Name"] = df2["Name"].str.strip()

In [21]:
common_players = set(df1["Name"]).intersection(set(df2["Name"]))

print("Common Players:", len(common_players))

Common Players: 161

In [22]:
only_in_df1 = set(df1["Name"]) - set(df2["Name"])
only_in_df2 = set(df2["Name"]) - set(df1["Name"])

print("Only in df1:", len(only_in_df1))
print("Only in df2:", len(only_in_df2))

Only in df1: 444
Only in df2: 100

In [23]:
only_df1 = sorted(set(df1["Name"]) - set(df2["Name"]))
only_df2 = sorted(set(df2["Name"]) - set(df1["Name"]))

print("Only in df1:")
print(only_df1[:20])

print("\nOnly in df2:")
print(only_df2[:20])

Only in df1:
['A Ashish Reddy', 'A Chandila', 'A Chopra', 'A Choudhary', 'A Dananjaya', 'A Flintoff', 'A Kumble', 'A Mithun', 'A Mukund', 'A Nehra', 'A Singh', 'A Symonds', 'A Tomar', 'A Uniyal', 'AA Bilakhia', 'AA Chavan', 'AA Jhunjhunwala', 'AA Noffke', 'AB Agarkar', 'AB Barath']

Only in df2:
['A Kamboj', 'A Madhwal', 'A Raghuvanshi', 'A Taide', 'AA Kulkarni', 'AAP Atkinson', 'AJ Mandal', 'AM Ghazanfar', 'AR Sharma', 'AS Tendulkar', 'Abid Mushtaq', 'Abishek Porel', 'Akash Singh', 'Aravelly Avanish', 'Arshad Khan', 'Azmatullah Omarzai', 'BR Sharath', 'C Green', 'D Ferreira', 'D Madushanka']

In [24]:
merged = df1.merge( df2, on="Name",how="left")

In [25]:
merged.head()

,Unnamed: 0,Name,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,...,battingName,fieldingName,imgUrl,dob,battingStyles,longBattingStyles,bowlingStyles,longBowlingStyles,playingRoles,espn_url
0,0,A Ashish Reddy,280,31,196,18.0,270.0,400.0,28,10.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,A Badoni,161,18,139,2.0,12.0,12.0,11,14.64,...,A Badoni,Badoni,"https://img1.hscicdn.com/image/upload/f_auto,t...",3/12/1999,rhb,right-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/ayush-...
2,2,A Chandila,4,0,7,11.0,234.0,245.0,12,0.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,A Chopra,53,7,75,0.0,0.0,0.0,6,8.83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,A Choudhary,25,2,20,5.0,108.0,144.0,5,5.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
merged.colu

Index(['Unnamed: 0', 'Name', 'runs', 'boundaries', 'balls_faced', 'wickets',
       'balls_bowled', 'runs_conceded', 'matches', 'batting_avg',
       'batting_strike_rate', 'boundaries_percent', 'bowling_economy',
       'bowling_avg', 'bowling_strike_rate', 'catches', 'stumpings', 'ID',
       'longName', 'battingName', 'fieldingName', 'imgUrl', 'dob',
       'battingStyles', 'longBattingStyles', 'bowlingStyles',
       'longBowlingStyles', 'playingRoles', 'espn_url'],
      dtype='str')

In [ ]:
merged.runs.iloc[100:120]

In [40]:
merged.Name[104]

'C de Grandhomme'

In [ ]:
merged.drop(columns=['playingRoles','espn_url','ID','battingStyles','bowlingStyles','dob','fieldingName','battingName','longName','Unnamed: 0'], inplace=True)

,Name,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings,imgUrl,longBattingStyles,longBowlingStyles
0,A Ashish Reddy,280,31,196,18.0,270.0,400.0,28,10.00,142.86,15.82,8.89,22.22,15.00,8.0,0.0,NaN,NaN,NaN
1,A Badoni,161,18,139,2.0,12.0,12.0,11,14.64,115.83,12.95,6.00,6.00,6.00,8.0,0.0,"https://img1.hscicdn.com/image/upload/f_auto,t...",right-hand bat,right-arm offbreak
2,A Chandila,4,0,7,11.0,234.0,245.0,12,0.33,57.14,0.00,6.28,22.27,21.27,2.0,0.0,NaN,NaN,NaN
3,A Chopra,53,7,75,0.0,0.0,0.0,6,8.83,70.67,9.33,0.00,0.00,0.00,2.0,0.0,NaN,NaN,NaN
4,A Choudhary,25,2,20,5.0,108.0,144.0,5,5.00,125.00,10.00,8.00,28.80,21.60,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Yash Dayal,0,0,1,11.0,205.0,296.0,9,0.00,0.00,0.00,8.66,26.91,18.64,1.0,0.0,"https://img1.hscicdn.com/image/upload/f_auto,t...",right-hand bat,left-arm medium-fast
601,Yashpal Singh,47,5,67,0.0,0.0,0.0,4,11.75,70.15,7.46,0.00,0.00,0.00,3.0,0.0,NaN,NaN,NaN
602,Younis Khan,3,0,7,0.0,0.0,0.0,1,3.00,42.86,0.00,0.00,0.00,0.00,1.0,0.0,NaN,NaN,NaN
603,Yuvraj Singh,2754,367,2207,36.0,882.0,1091.0,129,21.35,124.78,16.63,7.42,30.31,24.50,29.0,0.0,NaN,NaN,NaN
604,Z Khan,117,13,141,102.0,2276.0,2860.0,99,1.18,82.98,9.22,7.54,28.04,22.31,20.0,0.0,NaN,NaN,NaN

In [ ]:
merged.shape